apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: k8s-live-demo
spec:
  ingressClassName: nginx
  rules:
    - host: demo1.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: {name: http}
          - path: /abc
            pathType: Prefix
            backend:
              service:
                name: web
                port: {name: http}
    - host: demo2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: {name: http}
